### ISSUE TITLE
Oracles/Frenzyhearth Faction

### ISSUE THREAD

**Issue by henke98** [WoWPortal/Paradox-Emu#9] opened 2019-11-05 17:27 UTC
**Describe the bug**
All quests that requires you to kill Frenzyheart or Oracles mobs are bugged since you cannot attack the mobs.

**To Reproduce**
1. Accept a quest from Frenzyheart Tribe or Oracles that require you to kill any mobs on the opposing faction.
2. Click on a mob required to do the quest
3. See error "Invalid Target"

**Expected behavior**
Attack the target

**Comment by WoWPortal** [comment] 2019-11-05 18:28
Fix is now being applied for the entire area

**Comment by Elounia** [comment] 2019-11-08 10:08
Bug confirmed. I did the whole quest chain and following quests are not completable:

https://www.wowhead.com/quest=12538/the-mist-isnt-listening (Not attackable)
https://www.wowhead.com/quest=12572/gods-like-shiny-things (I dug up around 15 of the Shiny Spots and only 1 contained Treasure - might work as intended)
https://www.wowhead.com/quest=12576/forced-hand (Not attackable)
https://www.wowhead.com/quest=12575/the-lost-mistwhisper-treasure (Not attackable, you can however loot the treasure and the required creature does spawn)

https://www.wowhead.com/quest=12705/will-of-the-titans (Not attackable)

**Comment by WoWPortal** [comment] 2019-11-08 19:13
The faction not attackable issue and main issue was resolved. Server will reboot soon. We were supposed to reboot and apply fixes last night but unfortunately did not have time.

**Comment by WoWPortal** [comment] 2019-11-09 22:44
Issue is now fixed

**Closed by WoWPortal** 2019-11-09 22:44 UTC
